import { v4 as uuidv4 } from 'uuid';

export function getSandboxRahmenvertraege() {
  return [
    {
      id: uuidv4(),
      bezeichnung: 'IT-Endgeräte (Laptops, Desktops, Monitore)',
      beschreibung:
        'Rahmenvertrag für die Beschaffung von IT-Endgeräten inkl. Laptops, Desktop-PCs, Monitore und Zubehör. Hersteller: Dell, Lenovo, HP.',
      lieferant: 'Bechtle AG',
      vertragsnummer: 'RV-2024-IT-001',
      gueltigAb: new Date('2024-01-01'),
      gueltigBis: new Date('2026-12-31'),
      cpvCodes: '30213100,30213300,30231000',
      maxVolumen: 500000,
      status: 'AKTIV',
      ansprechpartner: 'Thomas Schmidt',
      ansprechpartnerEmail: 't.schmidt@bechtle.de',
      ansprechpartnerTelefon: '+49 711 94670-100',
      zahlungsbedingungen: '30 Tage netto',
      skonto: '2% bei Zahlung innerhalb 14 Tagen',
      kuendigungsfrist: '3 Monate zum Quartalsende',
      produktkategorien: 'Laptops,Desktop-PCs,Monitore,Zubehör',
      abrufVolumen: 120000,
      mindestBestellwert: 100,
      dokumente: '[]',
      verlaengerungen: '[]',
      notizen: '',
      istSandbox: true,
    },
    {
      id: uuidv4(),
      bezeichnung: 'Büromöbel und Ergonomie',
      beschreibung:
        'Rahmenvertrag für Büromöbel inkl. Schreibtische, Bürostühle, Regale und ergonomisches Zubehör.',
      lieferant: 'Steelcase Deutschland GmbH',
      vertragsnummer: 'RV-2024-MOE-002',
      gueltigAb: new Date('2024-01-01'),
      gueltigBis: new Date('2025-06-30'),
      cpvCodes: '39130000,39110000',
      maxVolumen: 200000,
      status: 'ABGELAUFEN',
      ansprechpartner: 'Marina Weber',
      ansprechpartnerEmail: 'm.weber@steelcase.de',
      ansprechpartnerTelefon: '+49 89 35805-200',
      zahlungsbedingungen: '14 Tage netto',
      skonto: '',
      kuendigungsfrist: '6 Monate zum Jahresende',
      produktkategorien: 'Schreibtische,Bürostühle,Regale,Ergonomie-Zubehör',
      abrufVolumen: 185000,
      mindestBestellwert: 200,
      dokumente: '[]',
      verlaengerungen: '[]',
      notizen: 'Vertrag ausgelaufen. Nachfolgeverhandlungen laufen.',
      istSandbox: true,
    },
    {
      id: uuidv4(),
      bezeichnung: 'Bürobedarf und Verbrauchsmaterial',
      beschreibung:
        'Rahmenvertrag für Bürobedarf: Papier, Stifte, Ordner, Druckerpatronen, Toner und allgemeines Verbrauchsmaterial.',
      lieferant: 'Lyreco Deutschland GmbH',
      vertragsnummer: 'RV-2024-BUE-003',
      gueltigAb: new Date('2024-03-01'),
      gueltigBis: new Date('2025-12-31'),
      cpvCodes: '30192000,22800000,30190000',
      maxVolumen: 100000,
      status: 'GEKUENDIGT',
      ansprechpartner: 'Stefan Meier',
      ansprechpartnerEmail: 's.meier@lyreco.de',
      ansprechpartnerTelefon: '+49 2102 7003-50',
      zahlungsbedingungen: '45 Tage netto',
      skonto: '3% bei Zahlung innerhalb 10 Tagen',
      kuendigungsfrist: '3 Monate zum Quartalsende',
      produktkategorien: 'Papier,Stifte,Ordner,Druckerpatronen,Toner',
      abrufVolumen: 67000,
      mindestBestellwert: 50,
      dokumente: '[]',
      verlaengerungen: '[]',
      notizen: 'Gekündigt wegen Lieferproblemen. Übergang zu neuem Anbieter.',
      istSandbox: true,
    },
    {
      id: uuidv4(),
      bezeichnung: 'Drucker und Multifunktionsgeräte',
      beschreibung:
        'Rahmenvertrag für Drucker, Scanner, Multifunktionsgeräte und zugehöriges Verbrauchsmaterial.',
      lieferant: 'Ricoh Deutschland GmbH',
      vertragsnummer: 'RV-2024-DRU-004',
      gueltigAb: new Date('2024-04-01'),
      gueltigBis: new Date('2026-03-31'),
      cpvCodes: '30232000',
      maxVolumen: 150000,
      status: 'AKTIV',
      ansprechpartner: 'Klaus Richter',
      ansprechpartnerEmail: 'k.richter@ricoh.de',
      ansprechpartnerTelefon: '+49 511 6742-300',
      zahlungsbedingungen: '30 Tage netto',
      skonto: '2% bei Zahlung innerhalb 10 Tagen',
      kuendigungsfrist: '3 Monate zum Quartalsende',
      produktkategorien: 'Drucker,Scanner,Multifunktionsgeräte,Toner',
      abrufVolumen: 45000,
      mindestBestellwert: 150,
      dokumente: '[]',
      verlaengerungen: '[]',
      notizen: '',
      istSandbox: true,
    },
    {
      id: uuidv4(),
      bezeichnung: 'Laborchemikalien und Verbrauchsmaterial',
      beschreibung:
        'Rahmenvertrag für Laborchemikalien (Säuren, Lösungsmittel, Reagenzien), Einwegmaterial (Handschuhe, Pipettenspitzen) und Laborglas. Gefahrstofflagerung inklusive.',
      lieferant: 'Carl Roth GmbH + Co. KG',
      vertragsnummer: 'RV-2024-LAB-005',
      gueltigAb: new Date('2024-02-01'),
      gueltigBis: new Date('2026-06-30'),
      cpvCodes: '24300000,33140000,38437000',
      maxVolumen: 250000,
      status: 'AKTIV',
      ansprechpartner: 'Dr. Anna Fischer',
      ansprechpartnerEmail: 'a.fischer@carlroth.de',
      ansprechpartnerTelefon: '+49 721 5606-400',
      zahlungsbedingungen: '30 Tage netto',
      skonto: '2% bei Zahlung innerhalb 14 Tagen',
      kuendigungsfrist: '6 Monate zum Jahresende',
      produktkategorien: 'Chemikalien,Einwegmaterial,Laborglas,Pipettenspitzen',
      abrufVolumen: 98000,
      mindestBestellwert: 75,
      dokumente: '[]',
      verlaengerungen: '[]',
      notizen: 'Gefahrstoffbeauftragter muss bei jeder Bestellung informiert werden.',
      istSandbox: true,
    },
    {
      id: uuidv4(),
      bezeichnung: 'Konferenztechnik und AV-Systeme',
      beschreibung:
        'Rahmenvertrag für Videokonferenzsysteme, Beamer, interaktive Displays und Audio-/Videozubehör für Besprechungsräume.',
      lieferant: 'Logitech Europe S.A.',
      vertragsnummer: 'RV-2024-AV-006',
      gueltigAb: new Date('2024-06-01'),
      gueltigBis: new Date('2026-09-30'),
      cpvCodes: '32232000,32321200,38652000',
      maxVolumen: 180000,
      status: 'AKTIV',
      ansprechpartner: 'Patrick Braun',
      ansprechpartnerEmail: 'p.braun@logitech.com',
      ansprechpartnerTelefon: '+41 21 863-5100',
      zahlungsbedingungen: '60 Tage netto',
      skonto: '1.5% bei Zahlung innerhalb 14 Tagen',
      kuendigungsfrist: '3 Monate zum Quartalsende',
      produktkategorien: 'Videokonferenz,Beamer,Displays,Audio-Zubehör',
      abrufVolumen: 52000,
      mindestBestellwert: 250,
      dokumente: '[]',
      verlaengerungen: '[]',
      notizen: '',
      istSandbox: true,
    },
  ];
}

export function getSandboxBestellungen() {
  const now = new Date();
  const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000);

  return [
    // 1. BESTELLT — kleine Bestellung unter 1000€, kein Genehmigungsprozess, Rahmenvertrag mit Skonto
    {
      id: uuidv4(),
      artikelId: 'RV-DELL-U2723',
      artikelBezeichnung: 'Dell UltraSharp U2723QE Monitor 27"',
      marktplatz: 'RAHMENVERTRAG',
      lieferant: 'Bechtle AG',
      einzelpreis: 429.0,
      menge: 2,
      gesamtpreis: 858.0,
      skontoAbzug: 17.16,
      endpreis: 840.84,
      waehrung: 'EUR',
      status: 'BESTELLT',
      rahmenvertragNr: 'RV-2024-IT-001',
      genehmigungErforderlich: false,
      begruendung: 'Ersatz für defekte Monitore in Raum 3.12',
      bestelltAm: daysAgo(5),
      istSandbox: true,
    },
    // 2. GENEHMIGUNG_ANGEFORDERT — teure Bestellung, wartet auf Genehmigung
    {
      id: uuidv4(),
      artikelId: 'RV-DELL-5550',
      artikelBezeichnung: 'Dell Latitude 5550 Business Laptop',
      marktplatz: 'RAHMENVERTRAG',
      lieferant: 'Bechtle AG',
      einzelpreis: 1049.0,
      menge: 5,
      gesamtpreis: 5245.0,
      skontoAbzug: 104.9,
      endpreis: 5140.1,
      waehrung: 'EUR',
      status: 'GENEHMIGUNG_ANGEFORDERT',
      rahmenvertragNr: 'RV-2024-IT-001',
      genehmigungErforderlich: true,
      begruendung: 'Ausstattung neue Mitarbeiter Abteilung Entwicklung (5 Stellen ab 01.03.)',
      bestelltAm: daysAgo(2),
      istSandbox: true,
    },
    // 3. GENEHMIGT — genehmigt durch Admin
    {
      id: uuidv4(),
      artikelId: 'RV-RICOH-C3010',
      artikelBezeichnung: 'Ricoh IM C3010 Farblaser-Multifunktionsdrucker',
      marktplatz: 'RAHMENVERTRAG',
      lieferant: 'Ricoh Deutschland GmbH',
      einzelpreis: 2890.0,
      menge: 1,
      gesamtpreis: 2890.0,
      skontoAbzug: 57.8,
      endpreis: 2832.2,
      waehrung: 'EUR',
      status: 'GENEHMIGT',
      rahmenvertragNr: 'RV-2024-DRU-004',
      genehmigungErforderlich: true,
      genehmigungVon: 'Dr. Sabine Müller (Abteilungsleitung IT)',
      genehmigungAm: daysAgo(1),
      begruendung: 'Ersatz für defekten Drucker im 2. OG, Reparatur unwirtschaftlich',
      bestelltAm: daysAgo(3),
      istSandbox: true,
    },
    // 4. ABGELEHNT — abgelehnt mit Begründung
    {
      id: uuidv4(),
      artikelId: 'RV-LOG-RALLY',
      artikelBezeichnung: 'Logitech Rally Bar Videokonferenzsystem',
      marktplatz: 'RAHMENVERTRAG',
      lieferant: 'Logitech Europe S.A.',
      einzelpreis: 2590.0,
      menge: 2,
      gesamtpreis: 5180.0,
      skontoAbzug: 77.7,
      endpreis: 5102.3,
      waehrung: 'EUR',
      status: 'ABGELEHNT',
      rahmenvertragNr: 'RV-2024-AV-006',
      genehmigungErforderlich: true,
      ablehnungsgrund: 'Budget für Konferenztechnik in Q1 bereits ausgeschöpft. Bitte im Q2 erneut beantragen.',
      begruendung: 'Ausstattung der neuen Besprechungsräume 4.01 und 4.02',
      bestelltAm: daysAgo(7),
      istSandbox: true,
    },
    // 5. BESTELLT — Marktplatz-Bestellung (Amazon Business), ohne Rahmenvertrag, ohne Skonto
    {
      id: uuidv4(),
      artikelId: 'AMZ-B07XJ8C8F5',
      artikelBezeichnung: 'Logitech MX Master 3S Maus',
      marktplatz: 'AMAZON_BUSINESS',
      lieferant: 'Amazon Business',
      einzelpreis: 89.99,
      menge: 3,
      gesamtpreis: 269.97,
      skontoAbzug: 0,
      endpreis: 269.97,
      waehrung: 'EUR',
      status: 'BESTELLT',
      genehmigungErforderlich: false,
      bestelltAm: daysAgo(10),
      istSandbox: true,
    },
    // 6. GENEHMIGUNG_ANGEFORDERT — Mercateo-Bestellung, ohne RV, hoher Betrag
    {
      id: uuidv4(),
      artikelId: 'MER-9182736',
      artikelBezeichnung: 'Ergotron LX Dual Monitor Arm (3er Set)',
      marktplatz: 'MERCATEO',
      lieferant: 'Ergotron',
      einzelpreis: 389.0,
      menge: 3,
      gesamtpreis: 1167.0,
      skontoAbzug: 0,
      endpreis: 1167.0,
      waehrung: 'EUR',
      status: 'GENEHMIGUNG_ANGEFORDERT',
      genehmigungErforderlich: true,
      begruendung: 'Ergonomie-Maßnahme nach Arbeitsplatzbegehung. Empfehlung Betriebsarzt.',
      bestelltAm: daysAgo(1),
      istSandbox: true,
    },
    // 7. BESTELLT — Laborbedarf, kleine Bestellung
    {
      id: uuidv4(),
      artikelId: 'RV-ROTH-NITRIL-M',
      artikelBezeichnung: 'Nitrilhandschuhe puderfrei Gr. M, 200 Stück',
      marktplatz: 'RAHMENVERTRAG',
      lieferant: 'Carl Roth GmbH + Co. KG',
      einzelpreis: 11.9,
      menge: 10,
      gesamtpreis: 119.0,
      skontoAbzug: 2.38,
      endpreis: 116.62,
      waehrung: 'EUR',
      status: 'BESTELLT',
      rahmenvertragNr: 'RV-2024-LAB-005',
      genehmigungErforderlich: false,
      begruendung: 'Quartalsweise Nachbestellung Laborverbrauchsmaterial',
      bestelltAm: daysAgo(14),
      istSandbox: true,
    },
    // 8. BESTELLT — Conrad-Bestellung, ohne RV
    {
      id: uuidv4(),
      artikelId: 'CON-2487561',
      artikelBezeichnung: 'Raspberry Pi 5 Starter Kit 8GB',
      marktplatz: 'CONRAD',
      lieferant: 'Conrad Electronic',
      einzelpreis: 124.99,
      menge: 2,
      gesamtpreis: 249.98,
      skontoAbzug: 0,
      endpreis: 249.98,
      waehrung: 'EUR',
      status: 'BESTELLT',
      genehmigungErforderlich: false,
      begruendung: 'Prototyping IoT-Projekt Gebäudeautomation',
      bestelltAm: daysAgo(8),
      istSandbox: true,
    },
  ];
}

export function getSandboxFrameworkContractItems() {
  return [
    {
      id: uuidv4(),
      titel: 'Dell Latitude 5550 Business Laptop (Rahmenvertrag)',
      beschreibung: '15.6 Zoll, Intel Core i7-1365U, 16GB RAM, 512GB SSD, Windows 11 Pro, 3 Jahre ProSupport. Abruf aus Rahmenvertrag IT-Endgeräte.',
      lieferant: 'Bechtle AG',
      cpvCodes: '30213100',
      preis: 1049.00,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-IT-001',
      artikelnummer: 'RV-DELL-5550',
      nachhaltigkeitslabel: 'Energy Star,EPEAT Gold',
      lieferzeit: '5-7 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Lenovo ThinkPad T14s Gen 4 (Rahmenvertrag)',
      beschreibung: '14 Zoll, AMD Ryzen 7 PRO 7840U, 16GB RAM, 512GB SSD, Windows 11 Pro. Abruf aus Rahmenvertrag IT-Endgeräte.',
      lieferant: 'Bechtle AG',
      cpvCodes: '30213100',
      preis: 1099.00,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-IT-001',
      artikelnummer: 'RV-LEN-T14S',
      nachhaltigkeitslabel: 'TCO Certified,Energy Star',
      lieferzeit: '5-7 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Dell UltraSharp U2723QE Monitor (Rahmenvertrag)',
      beschreibung: '27 Zoll 4K UHD IPS, USB-C Hub, 90W Power Delivery. Abruf aus Rahmenvertrag IT-Endgeräte.',
      lieferant: 'Bechtle AG',
      cpvCodes: '30231000',
      preis: 429.00,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-IT-001',
      artikelnummer: 'RV-DELL-U2723',
      nachhaltigkeitslabel: 'Energy Star,TCO Certified',
      lieferzeit: '3-5 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Steelcase Leap V2 Bürostuhl (Rahmenvertrag)',
      beschreibung: 'Ergonomischer Bürostuhl, LiveBack-Technologie, 4D-Armlehnen, Lordosenstütze, schwarz. Abruf aus Rahmenvertrag Büromöbel.',
      lieferant: 'Steelcase Deutschland GmbH',
      cpvCodes: '39110000',
      preis: 749.00,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-MOE-002',
      artikelnummer: 'RV-SC-LEAP-V2',
      nachhaltigkeitslabel: 'Blauer Engel',
      lieferzeit: '10-14 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Steelcase Ology Schreibtisch 160x80 (Rahmenvertrag)',
      beschreibung: 'Höhenverstellbarer Schreibtisch, elektrisch, Memory-Funktion, Kabelmanagement. Abruf aus Rahmenvertrag Büromöbel.',
      lieferant: 'Steelcase Deutschland GmbH',
      cpvCodes: '39130000',
      preis: 489.00,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-MOE-002',
      artikelnummer: 'RV-SC-OLOGY-160',
      nachhaltigkeitslabel: 'Blauer Engel',
      lieferzeit: '14-21 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Kopierpapier Premium A4 80g (Rahmenvertrag)',
      beschreibung: '2500 Blatt (5×500), weiß, FSC-zertifiziert. Abruf aus Rahmenvertrag Bürobedarf.',
      lieferant: 'Lyreco Deutschland GmbH',
      cpvCodes: '30192000',
      preis: 24.90,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-BUE-003',
      artikelnummer: 'RV-LYR-PAPIER-A4',
      nachhaltigkeitslabel: 'FSC,EU Ecolabel',
      lieferzeit: '1-2 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1568205612837-017257d2310a?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Ricoh IM C3010 Farblaser-MFP (Rahmenvertrag)',
      beschreibung: 'A3/A4 Farblaser-Multifunktionsdrucker, 30 Seiten/Min, Duplex, Netzwerk, WLAN. Abruf aus Rahmenvertrag Drucker.',
      lieferant: 'Ricoh Deutschland GmbH',
      cpvCodes: '30232000',
      preis: 2890.00,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-DRU-004',
      artikelnummer: 'RV-RICOH-C3010',
      nachhaltigkeitslabel: 'Blauer Engel,Energy Star',
      lieferzeit: '7-10 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Salzsäure 37% p.a. 2,5L (Rahmenvertrag)',
      beschreibung: 'HCl, ACS Reagenzienqualität, Gefahrstoffklasse 8. Abruf aus Rahmenvertrag Laborchemikalien. Gefahrstofflagerung inklusive.',
      lieferant: 'Carl Roth GmbH + Co. KG',
      cpvCodes: '24300000',
      preis: 22.50,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-LAB-005',
      artikelnummer: 'RV-ROTH-HCL37',
      nachhaltigkeitslabel: '',
      lieferzeit: '2-3 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Nitrilhandschuhe puderfrei Gr. M, 200 Stück (Rahmenvertrag)',
      beschreibung: 'Einweghandschuhe blau, EN 374, latexfrei. Abruf aus Rahmenvertrag Laborchemikalien.',
      lieferant: 'Carl Roth GmbH + Co. KG',
      cpvCodes: '33140000',
      preis: 11.90,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-LAB-005',
      artikelnummer: 'RV-ROTH-NITRIL-M',
      nachhaltigkeitslabel: '',
      lieferzeit: '1-2 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
    {
      id: uuidv4(),
      titel: 'Logitech Rally Bar Videokonferenz (Rahmenvertrag)',
      beschreibung: 'All-in-One Videobar, 4K Kamera, AI Framing, Beamforming-Mikrofone. Abruf aus Rahmenvertrag Konferenztechnik.',
      lieferant: 'Logitech Europe S.A.',
      cpvCodes: '32232000',
      preis: 2590.00,
      waehrung: 'EUR',
      rahmenvertragsNummer: 'RV-2024-AV-006',
      artikelnummer: 'RV-LOG-RALLY',
      nachhaltigkeitslabel: '',
      lieferzeit: '5-7 Werktage',
      bildUrl: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=400&h=300&fit=crop',
      verfuegbar: true,
      istSandbox: true,
    },
  ];
}
